### PR TITLE
possible mobile design

### PR DESCRIPTION
**Pull request by rfairooz**
Screenshot 2024-01-31 at 6 56 03 PM
Screenshot 2024-01-31 at 6 56 11 PM

### CODE REVIEW

**Review by NovaSagittarii — APPROVED** [review]
Looks good! The background gradient appears nicely with the glow effect on the buttons. For future reference, you can use CSS transformations `scaleX(-1)` to horizontally flip an asset instead of including an entirely new asset. It is fine in this case since it's a one-off and the file itself isn't too large.

**Comment by menthy-wu** [comment]
The assets looks so nice, but the box and the black background looks a bit weird

**Comment by rfairooz** [comment]
> Looks good! The background gradient appears nicely with the glow effect on the buttons. For future reference, you can use CSS transformations `scaleX(-1)` to horizontally flip an asset instead of including an entirely new asset. It is fine in this case since it's a one-off and the file itself isn't too large.

So I changed it a bit more and the new picture is what it looks like right now

**Comment by rfairooz** [comment]
> The assets looks so nice, but the box and the black background looks a bit weird

yes can you check the new look of it? I updated the pictures

**Pull request merged**
